### ISSUE TITLE
Height scrolling error

### ISSUE THREAD

**Issue by klivak** [spemer/vue-scroll-progress#1]
Hi, I used it on my Laravel + Vue project. 
Added it for global usage.
It's working, but only when I scroll for 30px maybe.
The height of the page is more than 100vh, but top line goes from 0 to 100% when I scroll for 20-30px.
http://prntscr.com/n2ogqp

Could you help me to understand what's wrong?

**Comment by spemer** [comment]
Hi,

It seems like the total height of the website that you capture, is not that high.
The top line goes 100% when scrollbar reaches bottom of the page.
So when if your website's total height is (100vh + 30px) and you scroll for 30px,
the top line will go to 100%.

I hope this can help you!

**Comment by klivak** [comment]
Hi, thanx for reply.
The height of the page is more than 100vh + 30px.
http://prntscr.com/n2zree

Really can't figure out what's wrong. Will try some test today.

**Comment by klivak** [comment]
Oh, I figure out what's wrong.
You are getting the height of the page when the page is loaded. 
But in my case, I am loading some data with ajax. And my page height has changed, but you plugin didn't get that's event.

I understand it when i set to body fixed height:
`body {
height: 3000px;
}`
and that's work.

P.S. Sorry for mistakes, hope you understand.
