### ISSUE TITLE
Tag position for html element

### ISSUE THREAD

**Issue by klivak** [spemer/vue-scroll-progress#2]
Hi, also I found out that you add some html tag outside the body tag, that's not nice. 

![Screenshot_1](https://user-images.githubusercontent.com/8767628/55067328-2f3fde80-5088-11e9-89f8-d91f44666517.png)

Could you fix it?

**Comment by spemer** [comment]
Hi,

I think the div with id="screen-shader" is not related to this library. Could you please check that the element still exists after you disable this library?

Thanks!

<img width="540" alt="스크린샷 2019-03-28 오전 12 37 06" src="https://user-images.githubusercontent.com/18291697/55089967-a2316f80-50f1-11e9-8781-fe887787f696.png">

**Comment by klivak** [comment]
Ok, I'll check it tomorrow. 
Maybe you're right and it can be some plugin for browser.

**Comment by klivak** [comment]
Yep, sorry, you were right, it was plugin for Chrome - "Night Shift" 🤦
