### ISSUE TITLE
vue-scroll-progress not working on vue-cli 3.x

### ISSUE THREAD

**Issue by LegenD1995** [spemer/vue-scroll-progress#3]
Hi
I try to use this plugin on vue cli 3.0.7

I put my content include one transition and router-view tag inside <VueScrollProgress> in my app.vue and set optional style for it... 
I build my project, then run it, but anything didn't change in my viewport

so I have a question:  **does it work on vue 3.x or not?**

**Comment by xaander1** [comment]
remove ` top:calc(100% - 4px) !important;` in css
